# -*- coding: utf-8 -*-
"""cf_knn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L6Y4KZNsboED2fRAuFamz4XMUUU8s5KQ

# 安装surprise包
"""

# !pip install surprise

"""# 导包"""

import sqlite3

import matplotlib.pyplot as plt
import numpy as np
# 第三方库
import pandas as pd
import seaborn as sns
from matplotlib.ticker import MultipleLocator
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

from surprise import KNNBasic
from surprise import Reader, Dataset, accuracy
from surprise import SVD
from surprise.model_selection import KFold
from surprise.model_selection import cross_validate



"""# KFlod验证"""

# In[]
path = "./drive/MyDrive/data/metadata/"

user_item_rating = pd.read_csv(path+'user_item_rating_2.csv')

# In[]
# itemCF

# 阅读器
reader = Reader(line_format='user item rating', sep=',')
# 载入数据
raw_data = Dataset.load_from_df(user_item_rating, reader=reader)
print(raw_data)
# 分割数据集
# kf = StratifiedKFold(n_splits=5)
# 构建模型
kf = KFold(n_splits=5)
# user_based=False 表示以item为基准计算相似度
knn_itemcf = KNNBasic(k=40, sim_options={'user_based': False})
# 训练数据集，并返回rmse误差  --- 10折交叉验证,以避免过拟合和欠拟合
temp_rmse = 0
temp_mae = 0
print("k=40 5折交叉验证 itemCF的平均准确率开始计算：")
for trainset, testset in kf.split(raw_data):
    knn_itemcf.fit(trainset)
    predictions = knn_itemcf.test(testset)
    temp_rmse = temp_rmse + accuracy.rmse(predictions, verbose=True)
    temp_mae = temp_mae + accuracy.mae(predictions, verbose=True)
# # k=1现在的平均准确率rmse：0.3520
# # k=40现在的平均准确率rmse：0.2761
print("k=40 itemCF的平均准确率rmse：%.6f" % (temp_rmse / 5))
print("k=40 itemCF的平均准确率mae：%.6f" % (temp_mae / 5))


# In[]
# userCF

# 阅读器
reader = Reader(line_format='user item rating', sep=',')
# 载入数据
raw_data = Dataset.load_from_df(user_item_rating, reader=reader)

# 分割数据集
kf = KFold(n_splits=5)
# 构建模型  # user_based=True 表示以user为基准计算相似度
knn_usercf = KNNBasic(k=40, sim_options={'user_based': True})
# 训练数据集，并返回rmse误差
temp_rmse2 = 0
temp_mae2 = 0
print("k=40 5折交叉验证 userCF的平均准确率开始计算：")
for trainset, testset in kf.split(raw_data):
    knn_usercf.fit(trainset)
    predictions = knn_usercf.test(testset)
    temp_rmse2 = temp_rmse2 + accuracy.rmse(predictions, verbose=True)
    temp_mae2 = temp_mae2 + accuracy.mae(predictions, verbose=True)
print("k=40 userCF的平均rmse：%.6f" % (temp_rmse2 / 5))
print("k=40 userCF的平均mae：%.6f" % (temp_mae2 / 5))

# k=40 itemCF的平均准确率rmse：0.984518
# k=40 itemCF的平均准确率mae：0.983965

# k=40 userCF的平均rmse：0.984518
# k=40 userCF的平均mae：0.983965

"""# cross_validate交叉验证"""

# In[]
path = "./drive/MyDrive/data/metadata/"

user_item_rating = pd.read_csv(path+'user_item_rating_2.csv')

# In[]
# itemCF

# 阅读器
reader = Reader(line_format='user item rating', sep=',')
# 载入数据
raw_data = Dataset.load_from_df(user_item_rating, reader=reader)
# cross_validate交叉验证
algo = KNNBasic()
cross_validate(algo, raw_data, measures = ['MAE','MSE'], cv = 5, verbose = True)

# MAE = 0.9840   MSE = 0.9693